In [15]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate([arr1,arr2])
print(arr)
arr3=np.hstack((arr1,arr2))
print(arr3)
arr4=np.vstack((arr1,arr2))
print(arr4)
arr5=np.dstack((arr1,arr2))
print(arr5)
arr=np.array([1,2,3,4,5,6])
arr6=np.array_split(arr,3)
print(arr)
print(arr6)
print(arr6[0])
print(arr6[1])
print(arr6[2])


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]
[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
